spring:
  r2dbc:
    url: ${DB_URL:r2dbc:mysql://localhost:3306/sapiece_gateway}
    username: ${DB_USERNAME:gateway}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 2
      max-size: 30
      max-acquire-time: 5s
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
jwt:
  secret: ${JWT_SECRET}
server:
  port: ${SERVER_PORT:8080}
logging:
  level:
    root: INFO
    com.sapiece.nova.sapiecegateway: INFO
    org.springframework.r2dbc: WARN
    org.springframework.security: WARN
    org.springframework.cloud.gateway: INFO
