apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-echo
  namespace: sapiece
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: grpc-echo}
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: 65}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
        - {type: Percent, value: 100, periodSeconds: 60}
        - {type: Pods, value: 2, periodSeconds: 60}
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - {type: Percent, value: 25, periodSeconds: 60}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-transcoder
  namespace: sapiece
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: grpc-transcoder}
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: 65}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
        - {type: Percent, value: 100, periodSeconds: 60}
        - {type: Pods, value: 2, periodSeconds: 60}
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - {type: Percent, value: 25, periodSeconds: 60}
